name: ci
on:
  - push
  - pull_request
env:
  TEST_DATABASE_URL: postgres://postgres@localhost:5432/bastetnect-test
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v.4.2.2
      - uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # v.1.245.0
        with:
          bundler-cache: true
      - run: bundle exec rubocop
      - run: bundle exec rake db:create db:migrate
        env:
          RAILS_ENV: test
      - run: bundle exec rspec spec
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
